name: Publish preview
description: Publishes changed projects to netlify and provides PR comment with the preview link
inputs:
  changed-glob:
    description: changed projects in glob pattern
    required: true
  repo-token:
    description: github token
    required: true
  netlify-token:
    description: netlify-auth-token
    required: true
outputs:
  preview-url:
    description: Preview URL

runs:
  using: composite
  steps:
    - name: Prepare publish folder
      shell: bash
      run: |
        mkdir _public
        for folder in $(echo "${{inputs.changed-glob}}" |sed 's/{packages\/(//g'|sed 's/)}//g'| tr '|' '\n')
        do
            echo "Processing ${folder}"
            if [[ -d "packages/${folder}/dist" ]]; then
                echo "dist folder found"
                pkgName=$(cat packages/${folder}/package.json | jq .name | sed 's/"//g')
                mkdir -p "_public/${pkgName}"
                cp -R "packages/${folder}/dist" "_public/${pkgName}/."
            fi
        done

    - name: Publish to netlify
      shell: bash
      run: |
        ls -lR _public/
        pnpm netlify deploy --site "cb4fc8b6-f7b4-46d6-9a7a-951be03a3326" --auth "${{inputs.netlify-token}}" --alias="pr-${{ github.event.number }}" -m "preview for PR-${{ github.event.number }}"

    - name: Provide preview link info
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
            ## Preview URL
            To ***preview*** components changed in this PR in current version of ***konnect*** use following URL:
            https://cloud.konghq.tech?pkgdomain=pr-${{ github.event.number }}--ui-shared-components
        GITHUB_TOKEN: ${{ inputs.repo-token }}
