name: Publish preview
description: Publishes changed projects to netlify and provides PR comment with the preview link
inputs:
  filter:
    description: changed projects in glob pattern
    required: true
  repo-token:
    description: github token
    required: true
  netlify-token:
    description: netlify-auth-token
    required: true
  short-sha:
    description: short-sha of current commit
    required: true
outputs:
  preview-url:
    description: Preview URL

runs:
  using: composite
  steps:
    - name: Prepare publish folder
      id: prepare_previews
      shell: bash
      run: |
        mkdir _public
        sha_short=$(git rev-parse --short HEAD)
        echo "::set-output name=sha_short::${sha_short}"
        for folder in $(echo "${{inputs.filter}}" |sed 's/{packages\/(//g'|sed 's/)}//g'| tr '|' '\n')
        do
            echo "Processing previews for ${folder}"
            if [[ -d "packages/${folder}/dist" ]]; then
                echo "dist folder found"
                pkgName=$(cat packages/${folder}/package.json | jq .name | sed 's/"//g')
                mkdir -p "_public/${pkgName}"
                cp -R "packages/${folder}/dist" "_public/${pkgName}/."
                cd "packages/${folder}"
                tarBall=$(pnpm pack --pack-destination ../../_public)
                hashedTarBall="$(echo "${tarBall}" |sed 's/\.tgz//g')-${sha_short}.tgz"
                echo "${hashedTarBall}"
                mv "${tarBall}"  "${hashedTarBall}"
                cd ../../
            fi
        done

    - name: Publish to netlify
      shell: bash
      run: |
        ls -lR _public/
        pnpm netlify deploy --site "cb4fc8b6-f7b4-46d6-9a7a-951be03a3326" --auth "${{inputs.netlify-token}}" --alias="pr-${{ github.event.number }}" -m "preview for PR-${{ github.event.number }}"

    - name: Provide preview link info
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
            ## ***Preview*** components from this PR in consuming application

            ### for CDN consumption:
            for **Konnect** or any other app that supports pkgdomain use it in the query string
            example:
            https://cloud.konghq.tech?pkgdomain=pr-${{ github.event.number }}--ui-shared-components

            or add query string into script loader in your consuming application code (example for `@kong-ui/demo-component`):
            ```
            script: {
              libName: 'demo-component', // Required for UMD builds
              url: 'https://packages.konghq.tech/@kong-ui/demo-component@0.5.0/dist/demo-component.umd.js?pkgdomain=pr-${{ github.event.number }}--ui-shared-components',
              type: 'umd'
            ```

            ### for NPM consumption:
            update `package.json` of consuming application and reference component package via tarball preview (example for `@kong-ui/demo-component`):
            ```
            "@kong-ui/demo-component": "https://pr-${{ github.event.number }}--ui-shared-components.netlify.app/kong-ui-demo-component-0.4.0-${{steps.prepare_previews.outputs.sha_short}}.tgz",
            ```
        GITHUB_TOKEN: ${{ inputs.repo-token }}
