name: Publish preview
description: Publishes changed projects to netlify and provides PR comment with the preview link
inputs:
  filter:
    description: changed projects in glob pattern
    required: true
  repo-token:
    description: github token
    required: true
  netlify-token:
    description: netlify-auth-token
    required: true
outputs:
  preview-url:
    description: Preview URL

runs:
  using: composite
  steps:
    - name: Prepare publish folder
      id: prepare_previews
      shell: bash
      run: |
        mkdir _public
        sha_short=$(git rev-parse --short HEAD)
        npm_instructions=""
        for folder in $(echo "${{inputs.filter}}" |sed 's/{(//g'|sed 's/)}//g'| tr '|' '\n')
        do
            echo "Processing previews for ${folder}"
            if [[ -d "${folder}/dist" ]]; then
                echo "dist folder found"
                pkgName=$(cat ${folder}/package.json | jq .name | sed 's/"//g')
                mkdir -p "_public/${pkgName}"
                cp -R "${folder}/dist" "_public/${pkgName}/."
                cd "${folder}"
                tarBall=$(pnpm pack --pack-destination ../../../_public)
                hashedTarBall="$(echo "${tarBall}" |sed 's/\.tgz//g')-${sha_short}.tgz"
                echo "${hashedTarBall}"
                mv "${tarBall}"  "${hashedTarBall}"
                fNTarBall=$(echo ${hashedTarBall} | sed 's/^.*_public\///')
                npm_instructions="${npm_instructions}yarn add \"${pkgName}@https://pr-${{ github.event.number }}--shared-ui-components.netlify.app/${fNTarBall}\""$'\r'$'\n'
                cd ../../../
            fi
        done

        echo "npm_instructions<<EOF" >> $GITHUB_ENV
        echo -e "$npm_instructions" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Publish to netlify
      shell: bash
      run: |
        ls -lR _public/
        pnpm netlify deploy --site "cb4fc8b6-f7b4-46d6-9a7a-951be03a3326" --auth "${{inputs.netlify-token}}" --alias="pr-${{ github.event.number }}" -m "preview for PR-${{ github.event.number }}"

    - name: Provide preview link info
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: pr_preview_consumption
        message: |
            ## ***Preview*** components from this PR in consuming application
            In consuming application project install preview versions of shared packages by running following commands:
            ```
            ${{env.npm_instructions}}
            ```
        GITHUB_TOKEN: ${{ inputs.repo-token }}
