[[headers]]
  for = "/mesh-manager/assets/*" # static files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

# see client/netlify/edge-functions/konnectEdgeProxy.ts for the details
[[edge_functions]]
  path = "/*"
  function = "konnectEdgeProxy"

# this is to do default redirect when PR preview is opened without a path
[[redirects]]
  from = "/"
  to = "/mesh-manager/"
  status = 301

#For SPO app, this is to make page refresh on deep link (path) working
[[redirects]]
  from = "/*"
  to = "/mesh-manager/"
  status = 200
