version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: kong-ui-shared-components
    path: ""
    text-resources:
      - path: src/locales/*.json
        format: nested-key-value
