name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      targets: ${{steps.changed_packages.outputs.targets}}
      filter: ${{steps.changed_packages.outputs.filter}}
      spec: ${{steps.changed_packages.outputs.spec}}
      unitTestFilter: ${{steps.changed_packages.outputs.unitTestFilter}}

    steps:
      - name: Remove preview consumption comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr_preview_consumption
          delete: true
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/
        with:
          force-install: 'true'

      - name: Check for pnpm-lock change
        id: lock-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            pnpm-lock.yaml

      - name: Getting changed packages
        id: changed_packages
        run: |
          lernaCommand="changed"
          if [[ "${{ steps.lock-changed.outputs.any_changed }}" == "true" ]]; then
            lernaCommand="ls"
          fi

          echo "lernaCommand: ${lernaCommand}"

          filter=""
          specPackages=""
          unitTestFilter=""

          # get the list of changed packages, grab the location
          for pkgFolder in $(lerna ${lernaCommand} --l --json|jq -r '.[].location')
          do
            # remove current folder from the location path
            pkgFolder="${pkgFolder/$(pwd)\//}"

            # add package path to pnpm filter
            filter="${filter}${pkgFolder}|"

            # if there is cypress tests in the package, add package path to cypress spec
            findRes=$(find "${pkgFolder}" -name "*.cy.ts" || true)
            if [[ -n "${findRes}" ]]; then
                specPackages="${specPackages}${pkgFolder},"
            fi

            findRes=$(find "${pkgFolder}" -name "*.spec.ts" || true)
            if [[ -n "${findRes}" ]]; then
                unitTestFilter="${unitTestFilter}${pkgFolder}|"
            fi
          done

          # remove trailing '|' from pnpm filter
          filter="{("$(echo "${filter}" | sed 's/|$//')")}"
          echo "filter=${filter}"

          unitTestFilter="{("$(echo "${unitTestFilter}" | sed 's/|$//')")}"
          echo "unitTestFilter=${unitTestFilter}"

          targets=$(echo "${unitTestFilter}"| sed 's/{(/\[\"/'| sed 's/)}/\"\]'/|sed 's/|/\"\,\"/g'| sed 's/packages\///g')
          echo "targets=${targets}"

          # remove trailing ',' from cypress spec
          specPackages=$(echo "${specPackages}" | sed 's/,$//')
          echo "specPackages=${specPackages}"

          # set github output
          echo "filter=${filter}" >> $GITHUB_OUTPUT
          echo "spec=${specPackages}" >> $GITHUB_OUTPUT
          echo "targets=${targets}" >> $GITHUB_OUTPUT
          echo "unitTestFilter=${unitTestFilter}" >> $GITHUB_OUTPUT
  build:
    name: Build And Test
    needs: install-dependencies
    # do not do anything unless changed package is detected
    if: ${{ needs.install-dependencies.outputs.filter != '{()}' }}
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/

      - name: Stylelint Packages
        run: pnpm --stream --filter "${{needs.install-dependencies.outputs.filter}}" run stylelint

      - name: Lint Packages
        run: pnpm --stream --filter "${{needs.install-dependencies.outputs.filter}}" run lint

      - name: Build Packages
        # The `...` syntax tells pnpm to include dependent packages
        run: pnpm --stream --filter "...${{needs.install-dependencies.outputs.filter}}..." run build

      - name: Run Unit Tests
        run: pnpm --stream --filter "${{needs.install-dependencies.outputs.unitTestFilter}}" run test:unit --coverage

      - name: Prepare Cypress
        if: ${{ needs.install-dependencies.outputs.spec != '' }}
        run: pnpm cypress install

      - name: Run Component Tests
        if: ${{ needs.install-dependencies.outputs.spec != '' }}
        uses: cypress-io/github-action@v4
        with:
          install: false
          command: pnpm run test:component:ci --spec ${{ needs.install-dependencies.outputs.spec }}

      - name: Report Component to Coveralls
        uses: coverallsapp/github-action@master
        continue-on-error: true
        if: ${{ needs.install-dependencies.outputs.spec != '' }}
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: component
          parallel: true

      - name: Upload Unit Test LCOV Reports
        uses: actions/upload-artifact@v3
        continue-on-error: true
        if: ${{ needs.install-dependencies.outputs.targets != '[]' }}
        with:
          name: unit-test-coverage
          path: packages/*/*/coverage/lcov.info

      - name: Upload Component Test Results
        uses: actions/upload-artifact@v3
        continue-on-error: true
        if: failure()
        with:
          name: component-test-failures
          path: |
            cypress/videos/
            cypress/screenshots/

      - name: Save Build Artifacts
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: package-dist-artifacts
          path: packages/*/*/dist

      - name: Publish Previews
        if: github.event_name == 'pull_request'
        run: |
          git config user.email "konnectx-engineers+kongponents-bot@konghq.com"
          git config user.name "Kong UI Bot"

          preid="pr.${{ github.event.pull_request.number }}.$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"
          tag="pr-${{ github.event.pull_request.number }}"
          echo "preid=${preid}"

          git checkout ${{ github.head_ref }}

          lerna version prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --conventional-prerelease --yes --amend --no-changelog

          npm_instructions=""
          for pkg in $(pnpm --stream --filter "${{needs.install-dependencies.outputs.filter}}" publish  --no-git-checks --access restricted --report-summary --tag "${tag}" | grep "+ "| sed 's/+ //')
          do
            pkg="@$(echo ${pkg}|cut -d'@' -f2)@${tag}"
            if [ "${npm_instructions}" != "" ]; then
              npm_instructions="${npm_instructions}\n"
            fi
            npm_instructions="${npm_instructions}${pkg}"
          done

          echo "npm_instructions<<EOF" >> $GITHUB_ENV
          echo -e "$npm_instructions" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Provide preview link info
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr_preview_consumption
          message: |
             ## ***Preview*** components from this PR in consuming application
             In consuming application project install preview versions of shared packages generated by this PR:
             ```
             ${{env.npm_instructions}}
             ```
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

  report-unit-coverage:
    name: Report Unit Coverage
    needs: [install-dependencies, build]
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ needs.install-dependencies.outputs.targets != '[""]' }}
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJSON(needs.install-dependencies.outputs.targets) }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Download Unit Test LCOV Reports
        uses: actions/download-artifact@v3
        with:
          name: unit-test-coverage
          path: coverage

      - name: Report Unit to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage/${{ matrix.container }}/coverage/lcov.info
          base-path: ${{ matrix.container }}
          flag-name: ${{ matrix.container }}
          parallel: true

  finish-coverage:
    name: Finish Coverage
    needs: [install-dependencies, report-unit-coverage]
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ needs.install-dependencies.outputs.targets != '[]' || needs.install-dependencies.outputs.spec != '' }}
    steps:
      - name: Finish Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  publish:
    if: ${{ github.event_name == 'push' }}
    name: Publish
    needs:
      - install-dependencies
      - build
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.KONGPONENTS_BOT_PAT }}

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: package-dist-artifacts
          path: packages/

      - name: Update package versions
        run: |
          git config user.email "konnectx-engineers+kongponents-bot@konghq.com"
          git config user.name "Kong UI Bot"
          lerna version --conventional-commits --create-release github --yes

      - name: Publish packages to NPM
        run: pnpm --stream --filter "${{needs.install-dependencies.outputs.filter}}" publish  --no-git-checks --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify-slack:
    name: Slack Notification
    if: ${{ always() && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Get aggregate Workflow status
        uses: technote-space/workflow-conclusion-action@v3

      - name: Send notification
        uses: edge/simple-slack-notify@v1
        env:
          SLACK_WEBHOOK_URL: ${{ env.WORKFLOW_CONCLUSION == 'failure' && secrets.SLACK_WEBHOOK_URL_ALERT || secrets.SLACK_WEBHOOK_URL_NOTIFY }}
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          success_text: '<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}|${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER})> workflow completed successfully :mario_luigi_dance:'
          failure_text: '<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}|${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER})> workflow failed :sad-panda:'
          fields: |
            [{ "title": "Repository", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}|${env.GITHUB_REPOSITORY}>", "short": true },
             { "title": "Branch", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/tree/${env.GITHUB_HEAD_REF || env.GITHUB_REF.substring(11)}|${env.GITHUB_HEAD_REF || env.GITHUB_REF.substring(11)}>", "short": true },
             { "title": "Revision", "value": "<${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/commit/${env.GITHUB_SHA}|${env.GITHUB_SHA.substring(0,7)}>", "short": true }]
