name: Verify PR
on:
  pull_request:
    branches:
      - main

jobs:
  check-packages:
    name: No PR preview references
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: No PR preview references
        uses: Kong/shared-actions/pr-previews/validate@main

